#!/bin/bash
DATE=`date "+%Y%m%d"`

for i in {1..29}
do
  touch /home/sybase/daily/log/dump_79_${DATE}.log
  touch /opt/sybase/backup/hbdsfk_cmp5_${DATE}.dmp
  DATE=`date -d "+$i day" "+%Y%m%d"`
done


