#!/bin/bash

####################
. /etc/profile
. ~/.bash_profile
####################

while read tablename
do

isql -Usa -Shbdsfkdb -PFK2015db78 -Dfktest -p -w999999 -Jcp936 << EOF
sp_spaceused $tablename
go
update statistics $tablename
go
update index statistics $tablename
go
sp_spaceused $tablename
go
exit
EOF


done < tablelist.txt
